### PR TITLE
Support Ruby 2.4

### PR DESCRIPTION
**Pull request by tombruijn**
Support Ruby 2.4 by bumping the json dependency.

I recommend #182 is merged beforehand.

### CODE REVIEW

**Comment by tombruijn** [comment]
Looks like it's still trying to install the wrong json version on 2.4 on travis. I'll have another look at it tomorrow

**Comment by longbai** [comment]
@tombruijn Thank you very much.

**Comment by bianjp** [comment]
It should be better to remove `json` dependency, as it's included in 1.9.3+ already, and this project only supports Ruby 2.1+.

**Comment by tombruijn** [comment]
Dependency removed, but looks like something changed in the json lib this gem relies on. The Ruby 2.4 specs keep failing.

**Comment by swelther** [comment]
It's green on my machine, but only with PR #182 merged. Maybe that's the reason it fails on travis?

**Comment by nazarok** [comment]
+1

**Comment by kesha-antonov** [comment]
Hello guys! Are you planning to merge?

**Comment by tombruijn** [comment]
Since the test suite fails dramatically on 2.4 I can't recommend merging this as is. Someone needs to take a look at fixing whatever is failing, but that's beyond my understanding of this gem.

**Comment by songjiayang** [comment]
Hi, @tombruijn  it's fixed in #195, check again please

**Comment by tombruijn** [comment]
Great! Thanks!

**Pull request closed without merging**
